-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module UsersApi.Object.User exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import UsersApi.Object
import UsersApi.Interface
import UsersApi.Union
import UsersApi.Scalar
import UsersApi.InputObject
import UsersApi.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

id : SelectionSet Int UsersApi.Object.User
id =
      Object.selectionForField "Int" "id" [] (Decode.int)


name : SelectionSet String UsersApi.Object.User
name =
      Object.selectionForField "String" "name" [] (Decode.string)


email : SelectionSet String UsersApi.Object.User
email =
      Object.selectionForField "String" "email" [] (Decode.string)


password : SelectionSet String UsersApi.Object.User
password =
      Object.selectionForField "String" "password" [] (Decode.string)
