# Use postgres/example user/password credentials
# https://hub.docker.com/_/postgres
version: '3.1'

services:

  localpostgres:
    container_name: server-axum-graphql-diesel-postgres
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      POSTGRES_USER: admin

volumes:
    pgdata:
