-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module UsersApi.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import UsersApi.Object
import UsersApi.Interface
import UsersApi.Union
import UsersApi.Scalar
import UsersApi.InputObject
import UsersApi.ScalarCodecs
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Json.Decode as Decode exposing (Decoder)
import Graphql.Internal.Encode as Encode exposing (Value)

type alias CreateUserRequiredArguments = { name : String
 , password : String
 , email : String }

createUser : CreateUserRequiredArguments
 -> SelectionSet decodesTo UsersApi.Object.User
 -> SelectionSet decodesTo RootMutation
createUser requiredArgs____ object____ =
      Object.selectionForCompositeField "createUser" [ Argument.required "name" requiredArgs____.name (Encode.string), Argument.required "password" requiredArgs____.password (Encode.string), Argument.required "email" requiredArgs____.email (Encode.string) ] (object____) (Basics.identity)
