-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UsersAPI.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import UsersAPI.InputObject
import UsersAPI.Interface
import UsersAPI.Object
import UsersAPI.Scalar
import UsersAPI.ScalarCodecs
import UsersAPI.Union


type alias CreateUserRequiredArguments =
    { name : String
    , password : String
    , email : String
    }


createUser :
    CreateUserRequiredArguments
    -> SelectionSet decodesTo UsersAPI.Object.User
    -> SelectionSet decodesTo RootMutation
createUser requiredArgs____ object____ =
    Object.selectionForCompositeField "createUser" [ Argument.required "name" requiredArgs____.name Encode.string, Argument.required "password" requiredArgs____.password Encode.string, Argument.required "email" requiredArgs____.email Encode.string ] object____ Basics.identity
