-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UsersAPI.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import UsersAPI.Scalar exposing (defaultCodecs)


type alias Id =
    UsersAPI.Scalar.Id


codecs : UsersAPI.Scalar.Codecs Id
codecs =
    UsersAPI.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
