-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UsersApi.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import UsersApi.Scalar exposing (defaultCodecs)


type alias Id =
    UsersApi.Scalar.Id


codecs : UsersApi.Scalar.Codecs Id
codecs =
    UsersApi.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
